### ISSUE TITLE
Responsiveness checklist

### ISSUE THREAD

**Issue by erolm-a** [denBot/WAD2-Group-Project#33]
- [x] Sharepage link is put in weird places sometimes (see https://screenshots.firefox.com/VbqpAAHTFDdF69aE/localhost)
- [x] both the navbar and the toolbars are compressed on mobile while they shouldn't. Probably a totally different structuring for smaller screens/mobile phones is required
- [x] the footer position is just too weird (https://screenshots.firefox.com/nF31lcgd3uoiWTP9/localhost)
